### ISSUE TITLE
SymCA and steady-state solve

### ISSUE THREAD

**Issue by bgoli** [PySCeS/PyscesToolbox#3]
Hi

Is it possible to use symca with a model that you cannot calculate a steady-state with? 

The use case is that you have a pathway with dummy kinetics where you cannot solve for  a steady state but would like to look at the control patterns.

**Comment by jmrohwer** [comment]
Currently it is not possible but I agree that it is a good idea! I am not sure how many changes it would involve. Of course the whole comparison of control coefficient values, etc., would have to be disabled. 

I tried the following.
1. Uncomment line 42 in analyse/_symca/_symca.py to prevent a MCA run on the model.
2. Then it runs into difficulties in line 149 of analyse/_symca/symca_toolbox.py when trying to construct the ES matrix, because the Pysces model has no elasticity coefficient attributes. I suppose in the case where you have dummy kinetics you'd restrict yourself to substrate and product elasticities, unless you have a way of specifying allosteric elasticities that you want to include by hand. 

But I'm not sure how much of the rest of symca hinges on this. I think it is important because one of the points we are trying to make is that the expressions give you some info on control structure even when no detailed kinetic model is available.

Carl?

**Comment by bgoli** [comment]
Ah good to hear, I could imagine being able to do something (completely arbitrary example) like:

> R1:
> A = B
> A\*B\*C

> R2:
> B = C
> B\*C

Would analysing something like this be useful/desirable? If it would help we could modify PySCeS to generate the elasticity attributes without actually needing to calculate them.

**Comment by exe0cdc** [comment]
Like Johann said, it is not currently possible. It is, however, an important and desirable feature.

The issue on line 149 is that during the construction of the ES matrix I check if an elasticity coefficient has a value of zero, in which case I add "0" to the matrix rather than "ecReaction_Species". This is done to simplify the control coefficient expressions (and it saves quite a bit of time).  I haven't looked at the code in quite a while, but I guess a rather simple solution would be to have a setting to disable this functionality, or to determine if an elasticity is expected to be zero in another way (i.e. if a reaction has no interaction with a certain species). I'm sure there will not be any need for changes to pysces. 

I'll work on a solution and post an update on my progress by the end of the week.

**Comment by jmrohwer** [comment]
One should definitely include the zero elasticities, otherwise the expressions become very unwieldy even for small models! One way would be just to include substrates and products and set all other elasticities zero. If there is an added option to manually specify the existence of additional elasticities (e.g. allosteric interactions), then this would be an additional bonus. Question is where to do this. If it is in the PySCeS input file, then PySCeS may need to be modified. Alternatively Carl you may suggest a psctb specific solution.
I definitely see merit in this. Also in our teaching we have used PySCeS purely for structural analysis of networks to detect fluxrelationships and conservation relationships. We normally set all rate equations equal to "v" and then set "v=1" in the initialisations. As soon as you have branches in your system, it won't be able to calculate a numerical steady state, but the structural analysis is valid nevertheless.

**Comment by bgoli** [comment]
I agree but have a suggestion w.r.t. the zero elasticities. PySCeS actually does this for you already as when it parses the rate equations it already identifies metabolites that are not in the stoichiometry as modifiers. 

For example, I've taken `pysces_test_linear1.psc` and modified *R2* with a arbitrary modifier *s2* which appears as a reagent in *R3* and and *R4*:

>R2:
>    s0 = s1
>    k3*s0 - s2*k4*s1

using PySCeS:

>In: mod = pysces.model('test_symca.psc')
>In: mod.modifiers
>Out: (('R4', ()), ('R1', ()), ('R2', ('s2',)), ('R3', ()))

in fact playing around with this, there is an even better way to do it and that is to use mod.\_\_nDict\_\_ directly:

>In: mod.\_\_nDict\_\_
>Out: 
> 'R2': {'AllReagents': [('self.s0', -1.0), ('self.s1', 1.0)],
>  'Modifiers': ['self.s2'],
>  'Params': ['self.k3', 'self.k4'],
>  'RateEq': 'self.k3*self.s0-self.s2*self.k4*self.s1',
>  'Reagents': {'self.s0': -1.0, 'self.s1': 1.0},
>  'Type': 'Rever',
>  'compartment': None,
>  'name': 'R2'},

Where you can extract the reagents and modifiers, per reaction, directly. I'm not sure how you want to go about the implementation but one option would be:

- on solver/mca evaluation fail
- give warning message as such and what it will now assume
- symca uses \_\_nDict\_\_ to determine non-zero elasticities (reagents and modifiers)

b.

**Comment by jmrohwer** [comment]
Implemented in `Symca` class with `ignore_steady_state=True` argument:
https://pyscestoolbox.readthedocs.io/en/1.0.0/_modules/psctb/analyse/_symca/_symca.html#Symca
https://pyscestoolbox.readthedocs.io/en/1.0.0/psctb.analyse._symca.html#psctb.analyse._symca._symca.Symca
